services:
  backend:
    build: ./server
    ports:
      - "${PORT}:5000"
    volumes:
      - ./server:/server
      - /server/node_modules
    env_file:
      - ./server/.env
    environment:
       NODE_ENV: ${NODE_ENV}
       LOCAL_URI: ${LOCAL_URI}
       MONGO_URI: ${MONGO_URI}
    depends_on:
      - mongo
  
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    env_file:
      - ./frontend/.env
    environment:
      VITE_API_URL : ${VITE_API_URL}
      LOCAL_VITE_API_URL : ${LOCAL_VITE_API_URL}

  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: