name: Auto tasks Update

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs: 
  update-tasks : 
    runs-on : ubuntu-latest

    steps: 
    - name : Checkout repository
      uses : actions/checkout@v3

    - name : Setup Node.js
      uses : actions/setup-node@v3
      with:
        node-version: '18'
    
    - name : Install dependencies
      working-directory : ./server
      run : npm install 
    
    - name: Create and run tasks script
      working-directory: ./server
      run: |
        cat << 'EOF' > run-cron.js
        const connectDb = require("../../server/config/db")
        const { updateOverdueTasks, resetDailyStreakStatus } = require('./job/cronJob');
    
        async function runTasks() {
          try {

            console.log('Connecting to database...')
            await connectDb();

            console.log('Starting update overdue tasks...');
            await updateOverdueTasks();
    
            console.log('Starting reset daily streak status...');
            await resetDailyStreakStatus();
    
            console.log('All tasks completed successfully');
            process.exit(0);
          } catch (error) {
            console.error('Error running scheduled tasks:', error);
            process.exit(1);
          }
        }
    
        runTasks();
        EOF
    
    - name : Run cron tasks
      working-directory : ./server
      env:
          NODE_ENV: production
          MONGO_URI: ${{ secrets.MONGO_URI }}
          
      run: node run-cron.js